addressbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
)

urlpatterns += staticfiles_urlpatterns()

contacts/urls.py
from django.conf.urls import patterns, include, url
from contacts import views

urlpatterns = patterns(
    '',
    url(r'^$', views.ContactList.as_view(), name='contact_list'),
    url(r'^new/$', views.ContactNew.as_view(), name='contact_new'),
    url(
        r'^(?P<contact_id>\d+)/$', 
        views.ContactDetail.as_view(), 
        name='contact_detail'
    ),
    url(
        r'^(?P<contact_id>\d+)/edit/$', 
        views.ContactEdit.as_view(), 
        name='contact_edit'
    ),
)

contacts/models.py
from django.db import models

class Contact(models.Model):
    first_name = models.CharField(
        max_length=255, default=None, help_text='First Name:'
    )
    last_name = models.CharField(
        max_length=255, default=None, help_text='Last Name:'
    )
    email = models.EmailField(
        max_length=255, default=None, help_text='Email:'
    )
    
    def __unicode__(self):
        return ' '.join([self.first_name, self.last_name])

contacts/forms.py
from django import forms
from contacts.models import Contact

class ContactForm(forms.ModelForm):    
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email',)

contacts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import QueryDict
from django.views.generic import View
from contacts.models import Contact
from contacts.forms import ContactForm

class ContactList(View):
    def get(self, request, *args, **kwargs):
        contacts = Contact.objects.all()
        context = {'contacts': contacts}
        return render(request, 'contacts/contact_list.html', context)


class ContactNew(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'contacts/contact_new.html')
        
    def post(self, request, *args, **kwargs):
        contact_form = ContactForm(request.POST)
        
        if contact_form.is_valid():
            contact_form.save()
            return redirect(reverse('contacts:contact_list'))
        else:
            return render(request, 'contacts/contact_new.html', status=422)


class ContactDetail(View):
    def get(self, request, *args, **kwargs):
        contact = get_object_or_404(Contact, pk=kwargs['contact_id'])
        context = {'contact': contact}
        return render(request, 'contacts/contact_detail.html', context)
        

class ContactEdit(View):
    def get(self, request, *args, **kwargs):
        contact = get_object_or_404(Contact, pk=kwargs['contact_id'])
        context = {'contact': contact}
        return render(request, 'contacts/contact_edit.html', context)
        
    def post(self, request, *args, **kwargs):
        contact = get_object_or_404(Contact, pk=kwargs['contact_id'])
        contact_form = ContactForm(request.POST, instance=contact)
        if contact_form.is_valid():
            contact_form.save()
            return redirect(
                reverse('contacts:contact_detail', args=(contact.id,))
            )
        else:
            context = {'contact': contact}
            return render(
                request, 'contacts/contact_edit.html', context, status=422
            )
    
    
            

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>Contacts{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <ul>
            <li>Contacts App</li>
        </ul>
    </header>
    
    {% block content %}{% endblock %}
    
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/contacts/_contact_fields.html
{% for field in contact_form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
{% endfor %}

templates/contacts/contact_detail.html
{% extends 'base.html' %}

{% block title %} | {{ contact }}{% endblock %}

{% block content %}
<h1>{{ contact }}</h1>
<h2>{{ contact.email }}</h2>
{% endblock %}

templates/contacts/contact_edit.html
{% extends 'base.html' %}
{% load contacts_extras %}
{% block title %} | Edit Contact{% endblock %}

{% block content %}
<h1>Edit Contact</h1>

<form method="post" action="{% url 'contacts:contact_edit' contact.id %}">
    {% csrf_token %}
    {% contact_fields contact %}
    <button>Update</button>
</form>
{% endblock %}

templates/contacts/contact_form.html
{% extends 'base.html' %}

{% block title %} | Add Contact{% endblock %}

{% block content %}
<h1>Add Contact</h1>

<form method="post" action="{% url 'contacts:contact_form' %}">
    {% csrf_token %}
    {% for field in contact_form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}
    <button>Add</button>
</form>
{% endblock %}

templates/contacts/contact_list.html
{% extends 'base.html' %}

<h1>Contacts</h1>

{% block content %}
<ul class="contact-list">
    {% for contact in contacts %}
        <li class="contact">{{ contact }}</li>
    {% endfor %}
</ul>
{% endblock %}

templates/contacts/contact_new.html
{% extends 'base.html' %}
{% load contacts_extras %}
{% block title %} | Add Contact{% endblock %}

{% block content %}
<h1>Add Contact</h1>

<form method="post" action="{% url 'contacts:contact_new' %}">
    {% csrf_token %}
    {% contact_fields %}
    <button>Add</button>
</form>
{% endblock %}